Switch refactor for210 (#1038)
* refactor of SwitchingFunction

* set up some tests for the switching function using 2.9.0 as reference

* Now the refactor passes the new tests

now passes rt20

lepton passes rt20b

rational passes rt42b

rational now is faster

passes rt20-q

cleaned cubic constructor

all rt20 test passes

small rationalization int the rational switches

* cleaned the unused variables

* const everithing!!!

* some rationalization in the parser

* changing inheritance with templates

* the bug in nativeq was altready patched, so there was no need to mess up in the merge

* adding tests for fastgaussian

* added fastGaussian

* clearer error for lepton

* added a templated pre-inlined rational

* moved the templated fastpow to Tools

* some files slipped in

* run astyle + removing some comments from codescan

* make lepton test for switch threaded

* Squashed commit of the following:

commit bd6fed1f7f631dff9e818aeab16fa2d941383b81
Author: Daniele Rapetti <5535617+Iximiel@users.noreply.github.com>
Date:   Fri Mar 8 11:07:21 2024 +0100

    compacted the lepton thing in a simpler struct

* addod some more precompiled rationals

* clarified ho the factory works

* comply with ruleof 3, need to DRY the class

* enfoced the multithreaded test for lepton

* rationalized ctor for switching lepton

* now it is easier to control the precompiled rational power

* removed "error: redefinition of default argument for ‘class T’"

* removed "error: redefinition of default argument for check"

* Another modification in tools: made the consts constexpr

* making codecheck happier, removing the == from the floating point

* And I forgot to reverse the signs...

* migrating to string_view, removing redeclaration of pi, floating point management in  doRational

* Noticed the user about the optimization in the rational

* added a very simple cltool for debugging faster the switching functions

* simplified plotswitch

* added a new option to switching function

* now --centerrange works using lepton to parse

* setting upTaylor for the rational gap

* updated changelog

* updated tests with correct values

* run astyle, it corrected also some file that I did not modified for this pr

* added <iomanip> header to switchingPlotter

---------

Co-authored-by: Daniele Rapetti <5535617+Iximiel@users.noreply.github.com>